{{- if .Values.mmtProbe.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmt-probe
  annotations:
    {{- range $k, $v := .Values.mmtProbe.deployment.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.mmtProbe.deployment.replicaCount }}
  selector:
    matchLabels:
      app: mmt-probe
  template:
    metadata:
      labels:
        app: mmt-probe
    spec:
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname }}
      {{- end }}
      containers:
      - name: mmt-probe
        image: "{{ .Values.mmtProbe.deployment.image.repository }}:{{ .Values.mmtProbe.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.mmtProbe.deployment.image.pullPolicy }}
        env:
        {{- range $k, $v := .Values.mmtProbe.deployment.env }}
        - name: "{{ $k }}"
          value: "{{ $v }}"
        {{- end }}
        command: {{ toJson .Values.mmtProbe.deployment.command }}
        args:
          - "-c"
          - {{ .Values.mmtProbe.deployment.args | quote }}
        resources:
{{ toYaml .Values.mmtProbe.deployment.resources | indent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: mmt
  labels:
    app: mmt
spec:
  selector:
    app: mmt-probe
  ports:
    - name: mmt
      port: {{ .Values.mmtProbe.service.port }}
      targetPort: {{ .Values.mmtProbe.service.port }}
      protocol: TCP

{{- end }}