{{- if .Values.monitoringPlan.enabled }}

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.monitoringPlan.name }}
  namespace: {{ .Values.monitoringPlan.namespace }}
spec:
  config: {{ .Values.monitoringPlan.config | quote }}

{{- end }}